"""add_homeroom_support

Revision ID: 3d7555b1b561
Revises: f49f2f6b76ed
Create Date: 2026-01-04 14:31:46.947018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d7555b1b561'
down_revision = 'f49f2f6b76ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homeroom_registers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('classroom_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('morning_boys', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('morning_girls', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('afternoon_boys', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('afternoon_girls', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('classroom_id', 'date', name='uq_homeroom_per_day')
    )
    op.create_index(op.f('ix_homeroom_registers_classroom_id'), 'homeroom_registers', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_homeroom_registers_date'), 'homeroom_registers', ['date'], unique=False)
    op.create_index(op.f('ix_homeroom_registers_id'), 'homeroom_registers', ['id'], unique=False)
    op.create_index(op.f('ix_homeroom_registers_teacher_id'), 'homeroom_registers', ['teacher_id'], unique=False)
    op.create_table('user_activity_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_activity_logs_action_type'), 'user_activity_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_user_activity_logs_created_at'), 'user_activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_activity_logs_id'), 'user_activity_logs', ['id'], unique=False)
    op.create_index(op.f('ix_user_activity_logs_user_id'), 'user_activity_logs', ['user_id'], unique=False)
    # Add is_homeroom column with default False for SQLite compatibility
    op.add_column('classes', sa.Column('is_homeroom', sa.Boolean(), nullable=False, server_default='0'))
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'TEACHER'"))
    op.alter_column('users', 'admin_premium_override',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'admin_premium_override',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'role',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'TEACHER'"))
    op.drop_column('classes', 'is_homeroom')
    op.drop_index(op.f('ix_user_activity_logs_user_id'), table_name='user_activity_logs')
    op.drop_index(op.f('ix_user_activity_logs_id'), table_name='user_activity_logs')
    op.drop_index(op.f('ix_user_activity_logs_created_at'), table_name='user_activity_logs')
    op.drop_index(op.f('ix_user_activity_logs_action_type'), table_name='user_activity_logs')
    op.drop_table('user_activity_logs')
    op.drop_index(op.f('ix_homeroom_registers_teacher_id'), table_name='homeroom_registers')
    op.drop_index(op.f('ix_homeroom_registers_id'), table_name='homeroom_registers')
    op.drop_index(op.f('ix_homeroom_registers_date'), table_name='homeroom_registers')
    op.drop_index(op.f('ix_homeroom_registers_classroom_id'), table_name='homeroom_registers')
    op.drop_table('homeroom_registers')
    # ### end Alembic commands ###

