"""Initial migration for students, register, and assessments modules

Revision ID: 437a29b13d2c
Revises: 
Create Date: 2025-11-25 18:55:28.271801

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '437a29b13d2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Create ENUMs safely (idempotent, PostgreSQL only)
    bind = op.get_bind()
    is_postgresql = bind.dialect.name == 'postgresql'
    
    if is_postgresql:
        # Create assessmenttype ENUM if it doesn't exist
        assessment_enum = postgresql.ENUM(
            'QUIZ',
            'HOMEWORK',
            'PROJECT',
            'TEST',
            'EXAM',
            name='assessmenttype',
            create_type=False
        )
        assessment_enum.create(bind, checkfirst=True)
        
        # Create registerstatus ENUM if it doesn't exist
        register_enum = postgresql.ENUM(
            'PRESENT',
            'ABSENT',
            'LATE',
            'EXCUSED',
            name='registerstatus',
            create_type=False
        )
        register_enum.create(bind, checkfirst=True)
    
    # Choose ENUM type based on database
    if is_postgresql:
        assessment_type_enum = postgresql.ENUM(
            'QUIZ',
            'HOMEWORK',
            'PROJECT',
            'TEST',
            'EXAM',
            name='assessmenttype',
            create_type=False
        )
        register_status_enum = postgresql.ENUM(
            'PRESENT',
            'ABSENT',
            'LATE',
            'EXCUSED',
            name='registerstatus',
            create_type=False
        )
    else:
        # SQLite - use sa.Enum (no create_type needed)
        assessment_type_enum = sa.Enum('QUIZ', 'HOMEWORK', 'PROJECT', 'TEST', 'EXAM', name='assessmenttype')
        register_status_enum = sa.Enum('PRESENT', 'ABSENT', 'LATE', 'EXCUSED', name='registerstatus')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('type', assessment_type_enum, nullable=False),
    sa.Column('total_marks', sa.Integer(), nullable=False),
    sa.Column('date_assigned', sa.Date(), nullable=False),
    sa.Column('date_due', sa.Date(), nullable=True),
    sa.Column('grade', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_id'), 'assessments', ['id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('parent_contact', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_table('assessment_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_scores_assessment_id'), 'assessment_scores', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessment_scores_id'), 'assessment_scores', ['id'], unique=False)
    op.create_index(op.f('ix_assessment_scores_student_id'), 'assessment_scores', ['student_id'], unique=False)
    op.create_table('register_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', register_status_enum, nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_register_records_date'), 'register_records', ['date'], unique=False)
    op.create_index(op.f('ix_register_records_id'), 'register_records', ['id'], unique=False)
    op.create_index(op.f('ix_register_records_student_id'), 'register_records', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_register_records_student_id'), table_name='register_records')
    op.drop_index(op.f('ix_register_records_id'), table_name='register_records')
    op.drop_index(op.f('ix_register_records_date'), table_name='register_records')
    op.drop_table('register_records')
    op.drop_index(op.f('ix_assessment_scores_student_id'), table_name='assessment_scores')
    op.drop_index(op.f('ix_assessment_scores_id'), table_name='assessment_scores')
    op.drop_index(op.f('ix_assessment_scores_assessment_id'), table_name='assessment_scores')
    op.drop_table('assessment_scores')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_assessments_id'), table_name='assessments')
    op.drop_table('assessments')
    # ### end Alembic commands ###

