"""Subscription constants"""

# Subscription Plans
SUBSCRIPTION_PLAN_FREE = "FREE"
SUBSCRIPTION_PLAN_PRO = "PRO"
SUBSCRIPTION_PLAN_SCHOOL = "SCHOOL"

# Subscription Statuses
SUBSCRIPTION_STATUS_ACTIVE = "ACTIVE"
SUBSCRIPTION_STATUS_CANCELED = "CANCELED"
SUBSCRIPTION_STATUS_TRIAL = "TRIAL"

# Valid plans list
VALID_SUBSCRIPTION_PLANS = [
    SUBSCRIPTION_PLAN_FREE,
    SUBSCRIPTION_PLAN_PRO,
    SUBSCRIPTION_PLAN_SCHOOL
]

# Valid statuses list
VALID_SUBSCRIPTION_STATUSES = [
    SUBSCRIPTION_STATUS_ACTIVE,
    SUBSCRIPTION_STATUS_CANCELED,
    SUBSCRIPTION_STATUS_TRIAL
]



